name: Run-Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    # Additional step to install linting dependencies
    - name: Install linting dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
      
    - name: Run flake8
      run: |
        flake8 pyfilehandling

  Pytests:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macOS-latest"]
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    # Assuming you have a requirements.txt file
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Additional step to install dependencies for coverage
    - name: Install additional dependencies for coverage
      run: |
        pip install pytest coverage

    - name: Run pytest with coverage
      run: |
        coverage run -m pytest
        coverage report --fail-under=50